Reuse koji build info from download_build_data
We use source heuristic in download_build_data and save it info
playground/metadata/buildinfo.json.

Later, we got build_info one more time from koji in the function
download_build, but we forgot to use source heuristic there.

The new version of function download_build_data returns modified
build_info using source heuristic and it is used in the function
download_source instead of just build_id.

  Traceback (most recent call last):
    File "/src/scripts/download-unpack-build.py", line 53, in <module>
      utils.download_source(build_info, output_source_dir)
    File "/src/assayist/processor/utils.py", line 235, in download_source
      source_url = re.sub(r'^git\+http', r'http', build_info['source'])
    File "/usr/lib64/python3.6/re.py", line 191, in sub
      return _compile(pattern, flags).sub(repl, string, count)
  TypeError: expected string or bytes-like object

  Uncaught exception. Entering post mortem debugging
  Running 'cont' or 'step' will restart the program
  > /usr/lib64/python3.6/re.py(191)sub()
  -> return _compile(pattern, flags).sub(repl, string, count)
  (Pdb) p string
  None